### PR TITLE
remove lodash dependency in favor of vanilla JS

### PR DESCRIPTION
**Pull request by therealparmesh**
`lodash` is outdated, bloated, slower, and not friendly to static type checking. This PR is just a recommendation.

### CODE REVIEW

**Comment by zxqx** [comment]
Definitely open to removing the lodash dependency (and agree with everything you said above), but part of the reason I used a `get` function here is to do deep object property access -- the `name` field for [field arrays](https://react-hook-form.com/api/usefieldarray) is in the format `{name}.{index}.value`, so this code change would break form validation for forms that use multi-input fields.

To see an example of what I mean, go to [Create Realm](https://deploy-preview-6--hypervibes.netlify.app/realm/create/basic-info) and type an invalid Ethereum address into an **Admin(s)** field and click **Next** -- notice the field does not get highlighted and no error message appears.

Thoughts?

**Comment by therealparmesh** [comment]
I was wondering if deep object property access was a use case. I scanned `name` props and didn't see any, so I felt emboldened. What if we wrote our own `get`? Something like this (but typed):

```js
function getDeep(object = {}, path = "") {
  let value = object;

  for (let key of path.split(".")) {
    try {
      value = value[key];
    } catch (e) {
      return;
    }
  }

  return value;
}
```

**Comment by zxqx** [comment]
100% down for that -- let's do it.

**Comment by therealparmesh** [comment]
Done!

**Comment by zxqx** [comment]
Looks good to me! Merging now.

**Pull request merged**
